### ISSUE TITLE
can it run multiple accounts at once ?

### ISSUE THREAD

**Issue by Ikhari** [xHaruke/Simple-DankGrinder#4]
can it run multiple accounts at once ? and does this script still work?

**Comment by Ikhari** [comment]
![unknown](https://user-images.githubusercontent.com/72252909/181414734-7ff09880-5ae7-49ea-b3ad-297f9751c538.png)

idk why but, always crash.

**Comment by xHaruke** [comment]
> ![unknown](https://user-images.githubusercontent.com/72252909/181414734-7ff09880-5ae7-49ea-b3ad-297f9751c538.png)
> 
> idk why but, always crash.

it is a npm issue I cannot do anything about it

**Comment by xHaruke** [comment]
> ![unknown](https://user-images.githubusercontent.com/72252909/181414734-7ff09880-5ae7-49ea-b3ad-297f9751c538.png)
> 
> idk why but, always crash.

should be fixed now

**Comment by Ikhari** [comment]
still same, even though re-deploy / create new app. the error still same.

**Comment by Ikhari** [comment]
> > ![unknown](https://user-images.githubusercontent.com/72252909/181414734-7ff09880-5ae7-49ea-b3ad-297f9751c538.png)
> > idk why but, always crash.
> 
> should be fixed now

nope, even though re-deploy / create a new app. the error is still same.

**Comment by xHaruke** [comment]
> > > ![unknown](https://user-images.githubusercontent.com/72252909/181414734-7ff09880-5ae7-49ea-b3ad-297f9751c538.png)
> > > idk why but, always crash.
> > 
> > 
> > should be fixed now
> 
> nope, even though re-deploy / create a new app. the error is still same.

is the channel id correct?

**Comment by xHaruke** [comment]
@Ikhari i updated the discord.js version just in case so it should work now

**Comment by Ikhari** [comment]
I have already tried it, it works for 1 loop but then crashes again. if u want to test it, I've many tokens (no problem if get banned) and I can become a tester too. just add my discord acc. **Ikhari#6969**
![image](https://user-images.githubusercontent.com/72252909/181722558-b28f029e-97f3-476b-b34b-b51d2c090e74.png)

**Comment by Ikhari** [comment]
ALREADY FIXED.
